java {
	sourceCompatibility = targetCompatibility = 8
	// withSourcesJar()
	// withJavadocJar()
}

def snapshot = project.release=="true" ? "" : "-SNAPSHOT"
def mod_version = project.mod_version + snapshot
def allowed_mc_version = project.allowed_mc_version
version = mod_version
group = project.maven_group

base {
	archivesName = "${mod_name}-${minecraft_version}"
}

//tasks.withType(JavaCompile).configureEach {
//	it.options.release = 21
//}

ploceus {
	setIntermediaryGeneration(2)
}


dependencies {
	modImplementation "net.fabricmc:fabric-loader:"+project.loader_version
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${minecraft_version}"
	// mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	//mappings loom.officialMojangMappings()
	mappings ploceus.mcpMappings(project.mcp_channel, project.mcp_mcversion, project.mcp_build)
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	//modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}

loom {

	// set access widener
	def accessWidenerFile = file('src/main/resources/modid.accesswidener')
	if(accessWidenerFile.exists()) {
		accessWidenerPath = accessWidenerFile
	}
	
	// set custom log4jconfig
	def log4jFile = file('src/main/resources/log4j.xml')
	if(log4jFile.exists()) {
		log4jConfigs.from(log4jFile)
	}
	
	runs {
		client {
			ideConfigGenerated = true
			vmArgs "-Dmodid.log.level=debug"
		}
		server {
			ideConfigGenerated = true
			vmArgs "-Dmodid.log.level=debug"
		}
	}
}

processResources {
	inputs.property "version", mod_version
	inputs.property "allowedMcVersion", allowed_mc_version

	filesMatching("fabric.mod.json") { file -> 
		expand "version": mod_version
        filter { String line ->
            line.replace('"minecraft": "*",', '"minecraft": "' + allowed_mc_version + '",')
        };
	}
}
