org.gradle.jvmargs=-Xmx3G
org.gradle.configuration-cache=true

# fabric
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# preprocessor
discombobulator_version=1.4

# mod
mod_name=PeacefulRNG
mod_version=1.0.0
maven_group=com.minecrafttas
release=false

# Mod properties
mod_description=Removes the RNG from certain food items when TASmod is installed
mod_url=https://minecrafttas.com
mod_sources=https://github.com/Unease/PeacefulRNG
mod_email=uneasepurse37@gmail.com