pluginManagement {
	repositories {
		mavenLocal() // For development purposes
		mavenCentral()
		gradlePluginPortal()
		maven { url = "https://maven.minecrafttas.com/main" }
		maven { url = "https://maven.fabricmc.net" }
		maven { url = "https://maven.ornithemc.net/releases" }
        maven { url = "https://maven.ornithemc.net/snapshots" }
	}
}

rootDir.listFiles().each { if (it.directory && new File(it, 'build.gradle').exists()) include ":${it.name}" }
